import Layout from 'layout'
import Head from 'next/head'
import React from 'react'

import { Stages } from '@/components/stages/stages'

import stagers from '@/data/stagers.json'

import styles from './styles.module.scss'

export const Stagers = () => {
	return (
		<>
			<Head>
				<title>Этапы</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<div className={styles.wrapperPageStagers}>
					<Stages stagers={stagers} />
				</div>
			</Layout>
		</>
	)
}
