import Layout from 'layout'
import Head from 'next/head'

import { About } from '@/components/about/about'
import { Heroimage } from '@/components/heroimage/Heroimage'
import { InfoSteeps } from '@/components/infoSteeps/infoSteeps'
import { Portfolio } from '@/components/portfolio/portfolio'
import { Stages } from '@/components/stages/stages'
import { Cooperation } from '@/components/сooperation/сooperation'

import stagers from '@/data/stagers.json'

export const Home = () => {
	let stagersFix = stagers.slice(0, 2)

	return (
		<>
			<Head>
				<title>Главная</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<Heroimage />
				<About />
				<InfoSteeps />
				<Portfolio />
				<Stages stagers={stagersFix} />
				<Cooperation />
			</Layout>
		</>
	)
}
