import Layout from 'layout'
import Head from 'next/head'
import React from 'react'

import { BrifContent } from '@/components/brifContent/brifContent'

export const Brif = () => {
	return (
		<>
			<Head>
				<title>Главная</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<BrifContent />
			</Layout>
		</>
	)
}
